version: "3"

services:

    PS:

         image: prestashop/prestashop

         volumes:

                 - ./data:/var/www/html

         ports:

               - "8099:80"

         restart: always

    DB:

        image: mysql:5.7

        restart: always

        environment:

                - MYSQL_DATABASE=exampledb

                - MYSQL_USER=userps

                - MYSQL_PASSWORD=passps

                - MYSQL_ROOT_PASSWORD=12345

        volumes:

            - ./db:/var/lib/mysql
            
            
    dbBackup:
          image: fradelg/mysql-cron-backup
          depends_on:
              - DB
          restart: always
          volumes:
                 - ./data:/backup
          environment:
              - MYSQL_USER=root
              - MYSQL_PASS=passps
              - MYSQL_DB=exampledb
              - CRON_TIME=50 1 * * *
              - MYSQL_HOST=db
              - MYSQL_PORT=80
              - TIMEOUT=10s
              - INIT_BACKUP=1
